#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: jonpvandermause
"""
# test out the gaussian potential

import matplotlib.pyplot as plt

# create gaussian
dists = [0.5, 1] # atom separation
grid_len = 2 # grid length
grid_space = 0.01


# plot the densities in the xy plane at z = 0
fig, axes = plt.subplots(1,2,sharey=True)

gausses = []
for n in range(len(dists)):
    dist = dists[n]
    
    xv, yv, zv, gauss = pot_rep(dist, grid_len, grid_space)
    gausses.append(gauss)
    
    xs = xv[:,:,0]
    ys = yv[:,:,0]
    dens = gauss[:,:,0]
    
    axes[n].contour(xs, ys, dens)
    axes[n].set_xlabel('x (angstrom)')
    axes[n].set_ylabel('y (angstrom)')
    axes[n].set_title('separation = '+str(dist)+' A')

plt.show()
