#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr  3 10:56:59 2018

@author: jonpvandermause
"""

alat = 0.75
vacuum = 5.29
ecut = 90

compute_H_energy(ecut=ecut,alat=alat,vacuum=vacuum,relax=False,\
                 verbose=True,dimer=True)

quick_density_gen(strain_vals=[alat], ecut = ecut,verbose=True)

dirname = '{}_a_{}_ecut_{}'.format('H2',alat,ecut)
file_path = os.environ['PROJDIR']+'/data/H2_DFT/temp_data/'+dirname+'/H2.rho.dat'
dens = rho_to_numpy(file_path,natoms=2)