#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr  3 19:29:59 2018

@author: jonpvandermause
"""

step_size = 0.159946
xs = np.arange(0, 124*step_size, step_size)
ys = np.arange(0, 124*step_size, step_size)
zs = np.arange(0, 124*step_size, step_size)
test1, test2, test3 = np.meshgrid(xs, ys, zs, indexing = 'ij')

plot_no = 62
cont = plt.contourf(test1[:,:,plot_no],test2[:,:,plot_no],dens[:,:,plot_no])
cbar = plt.colorbar(cont)
#plt.cplot()
plt.show()