#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr  3 20:30:34 2018

@author: jonpvandermause
"""

four = scipy.fftpack.fftn(dens)

plot_no = 0
fig = plt.figure()
cont = plt.contour(four[:,:,plot_no])
cbar = plt.colorbar(cont)
plt.show()